server:
  port: 5005

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/karthikeysaxena2507/ConfigServer
          clone-on-start: true